In [1]:
import os
import yaml
import pandas as pd
import numpy as np

with open("../configs/project_config.yaml") as f:
    config = yaml.safe_load(f)

EXAMPLES_PATH = "../esci-data/shopping_queries_dataset/shopping_queries_dataset_examples.parquet"
PRODUCTS_PATH = "../esci-data/shopping_queries_dataset/shopping_queries_dataset_products.parquet"

examples = pd.read_parquet(EXAMPLES_PATH, filters=[("product_locale", "=", "us")])
examples = examples[examples["small_version"] == 1].reset_index(drop=True)

FULL_TO_CODE = {"E": "Exact", "S": "Substitute", "C": "Complement", "I": "Irrelevant"}
LABEL_MAP = config["data"]["label_mapping"]
examples["relevance"] = examples["esci_label"].map(FULL_TO_CODE).map(LABEL_MAP)
assert examples["relevance"].isnull().sum() == 0

judged_product_ids = examples["product_id"].unique()
products_us = pd.read_parquet(PRODUCTS_PATH, filters=[("product_locale", "=", "us")])
products = products_us[products_us["product_id"].isin(judged_product_ids)].reset_index(drop=True)
del products_us

def build_product_text(row):
    parts = []
    missing = []
    for field, label in [
        ("product_title", "title"),
        ("product_brand", "brand"),
        ("product_bullet_point", "bullets"),
        ("product_color", "color"),
    ]:
        val = row[field]
        if pd.notna(val) and str(val).strip():
            parts.append(f"{label}: {val}")
        else:
            missing.append(field)
    return " [SEP] ".join(parts), missing

results = products.apply(build_product_text, axis=1)
products["product_text"] = results.apply(lambda r: r[0])
missing_counts = pd.Series([f for r in results for f in r[1]]).value_counts()
print("missing-field counts across catalogue:")
print(missing_counts)

os.makedirs("../data/processed", exist_ok=True)
products.to_parquet("../data/processed/products.parquet", index=False)
examples.to_parquet("../data/processed/judgments.parquet", index=False)
print("saved products.parquet:", products.shape)
print("saved judgments.parquet:", examples.shape)

products[["product_id", "product_title", "product_text"]].sample(3, random_state=42)

missing-field counts across catalogue:
product_color           155144
product_bullet_point     63627
product_brand            27191
Name: count, dtype: int64
saved products.parquet: (482105, 8)
saved judgments.parquet: (601354, 10)

,product_id,product_title,product_text
4215,B08KTP9JQP,Ace Tech Cellular LCD Screen Replacement Compa...,title: Ace Tech Cellular LCD Screen Replacemen...
137078,1495488594,The Everything Pet Rabbit Handbook: Your Ultim...,title: The Everything Pet Rabbit Handbook: You...
205595,B00APL0856,BW Technologies XT-XWHM-Y-NA GasAlertMax XT II...,title: BW Technologies XT-XWHM-Y-NA GasAlertMa...

In [2]:
val_ids_df = pd.read_csv("../data/processed/splits/validation_query_ids.csv")
val_query_ids = set(val_ids_df["query_id"])
print("validation queries:", len(val_query_ids))

val_examples = examples[examples["query_id"].isin(val_query_ids)].copy()
print("validation judged pairs:", len(val_examples))

val_queries = val_examples.drop_duplicates("query_id")[["query_id", "query"]].reset_index(drop=True)

relevant_lookup = (
    val_examples[val_examples["relevance"] >= 1]
    .groupby("query_id")["product_id"]
    .apply(set)
    .to_dict()
)
print("queries with at least 1 relevant product:", len(relevant_lookup))
print("queries with zero relevant products:", len(val_query_ids) - len(relevant_lookup))

validation queries: 4477
validation judged pairs: 89411
queries with at least 1 relevant product: 4477
queries with zero relevant products: 0

In [4]:
import time
import bm25s

corpus_texts = products["product_text"].tolist()

t0 = time.time()
corpus_tokens = bm25s.tokenize(corpus_texts, stopwords="en", show_progress=True)
print(f"tokenized in {time.time()-t0:.1f}s")

t0 = time.time()
retriever = bm25s.BM25(corpus=corpus_texts)
retriever.index(corpus_tokens)
print(f"indexed {len(corpus_texts)} products in {time.time()-t0:.1f}s")

product_id_array = products["product_id"].to_numpy()

Split strings:   0%|          | 0/482105 [00:00<?, ?it/s]

tokenized in 29.3s

BM25S Count Tokens:   0%|          | 0/482105 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/482105 [00:00<?, ?it/s]

indexed 482105 products in 24.1s

In [9]:
retriever.corpus = None  # return integer positions, not stored corpus text

query_texts = val_queries["query"].tolist()
query_tokens = bm25s.tokenize(query_texts, stopwords="en", show_progress=False)

t0 = time.time()
result_idx, result_scores = retriever.retrieve(query_tokens, k=100, show_progress=False)
elapsed = time.time() - t0

print(f"retrieved top100 for {len(query_texts)} queries in {elapsed:.1f}s -> {elapsed/len(query_texts)*1000:.1f}ms/query")
print("result_idx dtype:", result_idx.dtype, "shape:", result_idx.shape)

retrieved top100 for 4477 queries in 12.6s -> 2.8ms/query
result_idx dtype: int32 shape: (4477, 100)

In [10]:
latencies = []
for q in query_texts:
    t0 = time.time()
    q_tok = bm25s.tokenize([q], stopwords="en", show_progress=False)
    _ = retriever.retrieve(q_tok, k=100, show_progress=False)
    latencies.append(time.time() - t0)

latencies = np.array(latencies) * 1000  # ms

print(f"median: {np.median(latencies):.2f}ms")
print(f"p95: {np.percentile(latencies, 95):.2f}ms")
print(f"p99: {np.percentile(latencies, 99):.2f}ms")
print(f"max: {latencies.max():.2f}ms")

median: 2.57ms
p95: 4.95ms
p99: 6.26ms
max: 40.40ms

In [11]:
predicted_ids = product_id_array[result_idx]  # shape (4477, 100), row order matches val_queries

query_relevance = {
    qid: dict(zip(g["product_id"], g["relevance"]))
    for qid, g in val_examples.groupby("query_id")
}

def dcg(relevances):
    relevances = np.asarray(relevances, dtype=float)
    ranks = np.arange(1, len(relevances) + 1)
    return np.sum((2 ** relevances - 1) / np.log2(ranks + 1))

records = []
for i, row in val_queries.reset_index(drop=True).iterrows():
    qid = row["query_id"]
    preds = predicted_ids[i]
    rel_lookup = query_relevance[qid]

    retrieved_relevant = sum(1 for pid in preds if rel_lookup.get(pid, 0) >= 1)
    total_relevant = sum(1 for r in rel_lookup.values() if r >= 1)
    recall_100 = retrieved_relevant / total_relevant

    top10_rel = [rel_lookup.get(pid, 0) for pid in preds[:10]]
    ideal_rel = sorted(rel_lookup.values(), reverse=True)[:10]
    ndcg_10 = dcg(top10_rel) / dcg(ideal_rel) if dcg(ideal_rel) > 0 else 0.0

    mrr_10 = 0.0
    for rank, pid in enumerate(preds[:10], start=1):
        if rel_lookup.get(pid, 0) >= 1:
            mrr_10 = 1.0 / rank
            break

    records.append({"query_id": qid, "recall_100": recall_100, "ndcg_10": ndcg_10, "mrr_10": mrr_10})

metrics_df = pd.DataFrame(records)
print(metrics_df[["recall_100", "ndcg_10", "mrr_10"]].mean())
metrics_df.describe()

recall_100    0.460352
ndcg_10       0.310562
mrr_10        0.553209
dtype: float64

            query_id   recall_100      ndcg_10       mrr_10
count    4477.000000  4477.000000  4477.000000  4477.000000
mean    56162.521331     0.460352     0.310562     0.553209
std     34589.564914     0.320392     0.286632     0.439079
min         2.000000     0.000000     0.000000     0.000000
25%     25894.000000     0.181818     0.000000     0.000000
50%     56220.000000     0.437500     0.252795     0.500000
75%     86083.000000     0.750000     0.538680     1.000000
max    130539.000000     1.000000     1.000000     1.000000

In [12]:
import json

rank_records = []
for i, row in val_queries.reset_index(drop=True).iterrows():
    qid = row["query_id"]
    for rank, (pid, score) in enumerate(zip(predicted_ids[i], result_scores[i]), start=1):
        rank_records.append({"query_id": qid, "rank": rank, "product_id": pid, "bm25_score": score})

rankings_df = pd.DataFrame(rank_records)
os.makedirs("../artifacts", exist_ok=True)
rankings_df.to_parquet("../artifacts/bm25_validation_rankings.parquet", index=False)
print("saved rankings:", rankings_df.shape)

metrics_summary = {
    "n_queries": len(val_queries),
    "catalogue_size": len(products),
    "recall_100_mean": float(metrics_df["recall_100"].mean()),
    "ndcg_10_mean": float(metrics_df["ndcg_10"].mean()),
    "mrr_10_mean": float(metrics_df["mrr_10"].mean()),
    "recall_100_median": float(metrics_df["recall_100"].median()),
    "ndcg_10_median": float(metrics_df["ndcg_10"].median()),
    "mrr_10_median": float(metrics_df["mrr_10"].median()),
    "latency_ms_median": float(np.median(latencies)),
    "latency_ms_p95": float(np.percentile(latencies, 95)),
    "latency_ms_p99": float(np.percentile(latencies, 99)),
    "index_build_time_s": 33.4 + 25.6,
}

os.makedirs("../reports", exist_ok=True)
with open("../reports/bm25_metrics.json", "w") as f:
    json.dump(metrics_summary, f, indent=2)

print(json.dumps(metrics_summary, indent=2))

saved rankings: (447700, 4)
{
  "n_queries": 4477,
  "catalogue_size": 482105,
  "recall_100_mean": 0.4603518626716506,
  "ndcg_10_mean": 0.3105624680708995,
  "mrr_10_mean": 0.553209260027442,
  "recall_100_median": 0.4375,
  "ndcg_10_median": 0.25279507893794145,
  "mrr_10_median": 0.5,
  "latency_ms_median": 2.5670528411865234,
  "latency_ms_p95": 4.953241348266601,
  "latency_ms_p99": 6.255435943603511,
  "index_build_time_s": 59.0
}

In [13]:
metrics_labeled = metrics_df.merge(val_queries, on="query_id")

worst = metrics_labeled.sort_values("ndcg_10").head(10)
best = metrics_labeled.sort_values("ndcg_10", ascending=False).head(10)

title_lookup = dict(zip(products["product_id"], products["product_title"]))

def show_query(qid, query_text, n_preview=5):
    print(f"\nquery_id={qid}  query='{query_text}'")
    rel_lookup = query_relevance[qid]
    top_relevant = sorted(rel_lookup.items(), key=lambda x: -x[1])[:n_preview]
    print("  top judged-relevant products for this query:")
    for pid, rel in top_relevant:
        print(f"    [{rel}] {title_lookup.get(pid, '?')}")
    idx = val_queries.reset_index(drop=True).query("query_id == @qid").index[0]
    print("  top predicted (BM25):")
    for pid in predicted_ids[idx][:n_preview]:
        print(f"    [{rel_lookup.get(pid, 0)}] {title_lookup.get(pid, '?')}")

print("=" * 20, "WORST 10 (lowest NDCG@10)", "=" * 20)
for _, row in worst.iterrows():
    show_query(row["query_id"], row["query"])

print("\n" + "=" * 20, "BEST 10 (highest NDCG@10)", "=" * 20)
for _, row in best.iterrows():
    show_query(row["query_id"], row["query"])

==================== WORST 10 (lowest NDCG@10) ====================

query_id=38847  query='extra ordinary'
  top judged-relevant products for this query:
    [3] The Extraordinary Journey of the Fakir
    [3] The TNGA
    [3] Extraordinary: The Seeding
    [3] extraordinary: the stan romanek story
    [3] Extraordinary People: My Face is Killing Me
  top predicted (BM25):
    [0] The Ordinary The Daily Set (3 Pcs: The Ordinary Squalane Cleanser - The Ordinary Hyaluronic Acid 2% + B5 - The Ordinary Natural Moisturizing Factors + HA)
    [0] Colgate 360 Enamel Health Extra Soft Toothbrush for Sensitive Teeth
    [0] Rechargeable Light Bulbs, Back Up Battery Light Bulbs, 15W 80W Equivalent 6000K 1200mAh Battery Operated Light Bulb for Power Outage Hurricane, Emergency Lights for Home Power Failure, Pack of 2
    [0] The Ordinary 100% Plant-derived Squalane 30ml (Pack of 2)
    [0] The Ordinary Buffet 30ml

query_id=82709  query='pot container no smell'
  top judged-relevant products for this query:
    [3] Shrub Club - Smell Proof Jar, Black Glass with UV Protection, 1 Oz (500ml) Large Herb Container with 2 Way Humidity Pack, Airtight Herb Jars Keeps Contents Fresh (Wave)
    [3] Bud Tub plastic stash jar/storage container and shake separator for all types of herbs
    [3] Interplanetary Development – Glass Jar | Sealable Container | Blocks Harmful Rays | 100ml
    [3] Honeypuff Stash Jar (42 ML) Smell Proof Herb Storage Containers Jars with Seal Ring, Airtight Water Proof Aluminum Container to Keep Fresh(Red)
    [3] HIDE Stash Jar - Airtight Smell Proof Durable Multi-Use Portable Metal Herb Jar Container. Waterproof Aluminum Screw-top Lid Lock (Pack of 1, Black)
  top predicted (BM25):
    [0] Discreet Large Smell Proof Bag With Airtight Container and Odor Scent Proof Bags And Herb Grinder
    [0] Smell Proof Pouch - SMART STASH Smell Proof Bag - Small Smell Proof Containers (Black, 7x6)
    [0] Green Protected Airtight Herb Container - Quad Oz Smell Proof Glass Stash Jar (100 ml) comes with Humidity Pack to Keep Herbs Fresh for Months
    [0] Smell Proof Bag (9 x 6 x 4"), Waterproof Smell Proof Container with Removable Strip, Smell Proof Case with Lock Suitable for Herbs, Medicine, Spices, Grinder, Odor Proof Stash Bag (Blue)
    [0] LIVEN SK-J3201A Electric Hot Pot With Grill, Multifunctional Nonstick Coating Pot, 1300W, Perfect for 1-3 Person

query_id=1570  query='10gal white trash can without lid'
  top judged-relevant products for this query:
    [3] mDesign Small Rectangular Steel Trash Can, Narrow Wastebasket, Slim Garbage Container Bin, 2.4 Gallon for Bathroom, Bedroom, Kitchen, Home Office, Dorm, Recycling Waste Basket - Brushed Metal
    [3] United Solutions WB0084 Recycle Wastebasket, 1 Pack
    [3] Rubbermaid Small Kitchen Bathroom Trash Can, Under Sink Waste Basket, Plastic Beige 5 Gallons 8 Inch Wide
    [3] mDesign Slim Plastic Rectangular Small Trash Can Wastebasket, Garbage Container Bin with Handles for Bathroom, Kitchen, Home Office, Dorm, Kids Room - 10" High, Shatter-Resistant - White
    [2] HEMBOR 8 Gallon(30L) Trash Can, Brushed Stainless Steel Rectangular Garbage Bin with Lid and Inner Buckets, Soft Step and Silent Open Close Dustbin, Suit for Home Bathroom, Kitchen and Office
  top predicted (BM25):
    [0] Superio Small 2.5 Gallon Plastic Trash Can with Swing Top Lid, Waste Bin for Under Desk, Office, Bedroom, Bathroom- 10 Qt, White
    [0] CLTEC 10 Liter/2.6Gal Small Bathroom Trash Can with Lid Soft Close and Removable Inner Wastebasket, Slim Garbage Can, Step Trash Can for Bedroom Office Kids Room, Anti-Fingerprint Matte Finish, White
    [0] Touchless Motion-Sensor Automatic Trash Can - Buy 15Liter / 4 Gallon and Get 5Liter / 1.3 Gallon Mini Smart Trash Can Free, Waynmer Garbage Bin with Lid, Perfect for Office, Commercial Use, Kitchen
    [0] CTETC Slim Small Trash Can with Lid Soft Close and Removable Inner Wastebasket, Rectangular Narrow Garbage Can for Bathroom Bedroom Office, Anti-Fingerprint Matt Finish, 2.6Gal/10L, White
    [0] Superio Trash Can

query_id=1588  query='10kpendant settings without stones'
  top judged-relevant products for this query:
    [3] Anezus 60Pcs Pendant Trays, Bezel Pendant Trays Blanks with Glass Cabochons for Pendants Making and Jewelry Making, 5 Styles
    [3] LANBEIDE 40 Pcs Silver Pendant Trays with 40 Pcs Transparent Glass Cabochons, Round Pendant Bezels 1 inch/25mm for Photo Pendant Resin Craft Jewelry Making, Total 80 Pcs
    [3] KATARINA Diamond Palm Tree Pendant Necklace in 10k White Gold (1/10 cttw, J-K, SI2-I1)
    [3] Jewelili 14K Yellow Gold over Sterling Silver 1/4Cttw Natural White Round and Tapper Baguette Diamond Heart Pendant Necklace, 18'' Box chain
    [2] 12pcs Silver Plated Pearl Bead Cage Water Drop Spiral Locket Pendants Essential Oil Diffuser Necklace Bracelet DIY Charms Jewelry Making with Lava Stone
  top predicted (BM25):
    [0] Amazon Essentials Sterling Silver AAA Cubic Zirconia Bezel Stud Earrings (8mm)
    [0] Double Old Fashioned Whiskey Glass (Set of 4) with Granite Chilling Stones - 10 oz Heavy Base Rocks Barware Glasses for Scotch, Bourbon and Cocktail Drinks
    [0] Graham Products Glow in The Dark Rocks - Glowing Rocks for Aquarium Pebbles & Fish Tank Gravel - Aquarium Rocks for Fish Bowl - 450 Glow Rocks - Outdoor Garden Rocks & Landscaping Stones(Multicolored)
    [0] Graham Products Glow in The Dark Rocks 450PCS, Glowing Fish Tank Pebbles for Indoor & Outdoor Garden/Aquarium/Plant Pots/Walkway/Driveway, Blue
    [0] Sunny & Fun 11pc Balance Stepping Stones Obstacle Course for Kids | Rubber Grip Bottom River Stones in 4 Varying Sizes & Steepness | Indoor & Outdoor Toy Improves Coordination & Strength | Max 220 Lbs

query_id=1623  query='10x 7 x 2decorative pastry boxes 10x7x2 without window'
  top judged-relevant products for this query:
    [3] Frametory, Frame with Ivory Mat for Photo, Smooth Wood Grain Finish Easel Stand, Sawtooth Hangers, Real Glass Landscape/Portrait, Wall/Table Display (Rustic Grey, 8x10 Frame for 5x7 Photo, 1-Pack)
    [3] Golden State Art, 7 Pack Frames for One 11x14, Two 8x10, and Four 5x7 inch Pictures. Aluminum Photos Frame for Wall or Tabletop Display (Aluminum Style 1, Black)
    [3] Decor Grates AJH410-NKL Floor Register, 4" x 10", Nickel
    [3] Knape & Vogt John Sterling Colonial Style Decorative Shelf Bracket, 7-Inch, Black, RP-0090-7BK
    [3] Lawrence Frames 536280 Sutter Gold 8x10 Picture Frame
  top predicted (BM25):
    [0] NPLUX 20 Pack Pie Boxes 10x10x3inch Bakery Boxes with Window for Pies,Cheesecake and Chocolate Strawberries （White）
    [0] Spec101 Brown Bakery Boxes with Window, 25pk - 4in x 4in Cake Boxes, Party Favor Boxes, Candy Boxes, Dessert Boxes
    [0] HawHawToys Pie Boxes, 10 x 10 x 2.5 inches Bakery Boxes Cookies Boxes with Transparent Window for Dessert, Pastry, Cookie (Brown, 24)
    [0] Jucoan 20 Pack Kraft Cupcake Boxes Containers with Clear Display Window, Brown Cake Trays Holder for Cookies, Muffins Pastries, Holding 12 Standard Cupcakes for Mother's Day, Father's Day, Party
    [0] [25 Pack] O'Creme Small Bakery Cake Boxes With Window, 4x4x2.5, Cupcakes Donuts Cookies Pastries, For Wedding Treats Party Favors Showers Gift, White Paper Kraft Cardboard Mini Packaging Containers

query_id=1647  query='10x20 without walls'
  top judged-relevant products for this query:
    [3] CAVEPOP 8x10 White Picture Frame with Mat Set of 5, Made to Display 8x10” Without Mat, 5x7 with Mat - Large Wall Hanging Photo Frames, Collage Picture Frame Sets
    [3] Gallery Solutions Wall Mount Double Mat Picture Frame, 2-5" x 7" with Mat or 10" x 20" Without Mat, Gray/White
    [2] Finefrarm 12x16 Frames Display 11x14 Picture with Mat or 12 x 16 Photo Without Mats Black Picture Frames Wall Art for Living Room and Office Wall Mounting Decor
    [2] 11x14 Rustic Picture Frames Solid Wood - Display Pictures 9x12 or 8x10 with Mat or 11x14 Frame without Mat - Farmhouse Wooden Photo Frame 11x14 inch with 2 Mats for Wall Mounting or Table Top , 2 Set
    [2] upsimples 11x14 Picture Frame Set of 5,Display Pictures 8x10 with Mat or 11x14 Without Mat,Wall Gallery Photo Frames,White
  top predicted (BM25):
    [0] 10x20 Ft Pop up Canopy Party Wedding Gazebo Tent Shelter with Removable Side Walls White
    [0] 10x20 ft EZ Instant Pop up Canopy Carport,Party Tent Folding Gazebo with Removable Sidewalls and Wheeled Bag Waterproof
    [0] ABCCANOPY Instant Canopy SunWall 10x10 FT, 1 Pack Sidewall Only, Burgundy
    [0] ABCCANOPY Instant Canopy SunWall 10x10 FT, 1 Pack Sidewall Only, White
    [0] 10x20 ft EZ Instant Pop up Canopy Carport,Party Tent Folding Heavy Duty Gazebo with Removable Sidewalls and Wheeled Bag Waterproof

query_id=1718  query='11 year old girl gifts'
  top judged-relevant products for this query:
    [3] Doctor Unicorn Soft Unicorn Hooded Bathrobe Sleepwear - Unicorn Gifts for Girls (Rainbow, 10-11 Years)
    [3] DIY Unicorn Slime Kit for Girls,Best Present Toys Gifts for 7 8 9 10 11 12 Year Old Girls Birthday, Glitter Fluffy Slime Making Kit with Glow in The Dark Powder
    [3] Harry Potter Big Girls' Hermione Granger 'Hogwarts House Crest' Varsity Quidditch Raglan Nightgown, Gray, 14
    [3] Melissa & Doug Scratch Art Rainbow Mini Notes (125 ct) With Wooden Stylus
    [2] 11th BIRTHDAY Bracelet, 11th Birthday Charm Bracelet, Granddaughter Daughter Gift Idea, Eleventh Birthday Gift, 11 Year Old Birthday Bangle
  top predicted (BM25):
    [0] Toddler Kids Backpack w Husky Toy Wolf Stuffed Animal Plush Toys for 3 4 5 6 7 Year Old Girls Boys - Gifts for 3 4 5 6 7 Year Old Boy Girl - Husky Wolf Toy
    [0] 11th Birthday Gifts for Girls,11th Birthday Tiara and Sash Golden,11th Birthday Decorations Party Supplies,11th Birthday Decorations for Girls,Birthday Tiara for 11 Year Old Girls,11 Birthday Crown
    [0] Teddy Bear Stuffed Animal Backpack - Toys for 3 4 5 6 7 Year Old Girls Boy - 3-6 year old Girl Birthday Gift - Toddler Toys Boys Age 3 yr Kids Small Plush Mini Teddy Bears Plushie - Preschool Backpack
    [0] GirlZone Hair Chalk Set For Girls - 10 Piece Temporary Hair Chalks Color - Girl Toys For Girls Ages 8-12 - Birthday Gifts For Girls - Gifts For 7 8 9 10 11 Year Old Girls - Girls Toys 8-10 Years Old
    [0] 11th Birthday Gifts for girls,11th Birthday Tiara and Sash Silver,11th Birthday Decorations Party Supplies,It's My 11th Birthday Satin Sash Crystal Tiara Birthday Crown for 11th Birthday Party Decor

query_id=79830  query='piece dental high speed with led light'
  top judged-relevant products for this query:
    [3] AquaHomeGroup Teeth Whitening Kit with LED Light - Snow Teeth Whitener Set with Charcoal Toothpaste and Brushes - Tooth Whitening System All in One Carbamide Peroxide 3 X 3ml Gel Syringes
    [3] Dental Calculus Remover
    [2] Neitra Teeth Whitening Kit with LED Light, 10 Min Fast Teeth Whitening Results, (4) 3ml No Sensitive Whitening Gel, 5LED Teeth Whitener Accelerator, Teeth Whitening Kit at Home(Sensitive Series)
    [2] Smile Titan Teeth Whitening Kit, Teeth Whitening Gel (4) with 5X LED Accelerator Light and Tray Teeth Whitener
    [2] Teeth Whitening, Teeth Whitener, Bright Teeth Whitening Kit, 4 Syringes of 5ml Professional 35% Carbamide Peroxide Tooth Whitening Gel,LED Light, Mouth Tray.
  top predicted (BM25):
    [0] Dental Power Updated Modal Dental Teeth Whitening System LED Light Bleaching Machine Beauty Accelerator
    [0] Electric 35K RPM Marathon Type Polishing for Dental Lab Micromotor Polisher
    [0] Godox FV150 150W High Speed Sync Flash and Continuous LED Light,12000LUX, CRI 95+ TCLI 96+, 1/8000S HSS, Built-in Godox 2.4G Wireless X System, 1/8-1/1 or 7.0/10.0 Power Output,8 Pre-Programmed Effect
    [0] Panasonic Cordless Dental Water Flosser, Dual-Speed Pulse Oral Irrigator, Collapsible, Design for Travel - EW-DJ10-A
    [0] 35K RPM Dental Lab Jewelry Micromotor Polishing Micro Motor Hand Kit Fit Marathon

query_id=1388  query='100 days without sunlight book'
  top judged-relevant products for this query:
    [3] 24 Pieces 100th Day of School Bracelets Back to School Bracelets Happy 100th Day Wristbands Rubber Bracelets Assorted Color Bracelets for School Party Favors
    [0] Morndew 24 PCS Glitter Golden Crown Number 100 Cupcake Toppers for Baby 100th Birthday Party Baby Shower Wedding Party Decoration
    [0] JMH Magnifying Glass with Light, 30X Handheld Large Magnifying Glass 18LED Cold and Warm Light with 3 Modes, Illuminated Lighted Magnifier for Seniors Reading, Inspection, Coins, Jewelry, Exploring
    [0] Led Floor Lamp with 4 Color Temperature and Stepless Dimmer, Remote and Touch Control Floor Lamp, Adjustable Gooseneck Standing Lamp for Living Room
    [0] Rose Gold Happy 100 Days Banner, Kid's 100 Days Celebration,100th Day of School, 100 Days Theme Party Decoration
  top predicted (BM25):
    [0] Your First 100 Days In a New Executive Job: Powerful First Steps On The Path to Greatness
    [0] Solar Motion Sensor Light Outdoor - 800 Lumens 8 LED Spotlight 5W Security Solar Lights Outdoor IP66 Waterproof, Wireless Solar Flood Light for Porch Garden Patio Driveway Pathway, 2 Pack (Black)
    [0] Queen's designer Book Lover Reading Book Club A Room Without Books is Like A Body Without A Soul in Black Cotton Linen Decorative Throw Pillow Case Cushion Cover Square 18"X18
    [0] Happy Natural Light Therapy Lamp Simulated Sunlight Full Spectrum LED Lamp UV-Free 10000 Lux Bright Light Box Portable
    [0] Christopher Knight Home Cape Coral Outdoor Mesh Chaise Lounges, 4-Pcs Set, Grey

query_id=1414  query='100 oz water bottles without words'
  top judged-relevant products for this query:
    [3] Fidus Large Half Gallon/64OZ Motivational Water Bottle with Paracord Handle & Removable Straw - BPA Free Leakproof Water Jug with Time Marker to Ensure You Drink Enough Water Daily-Green/Purple
    [3] Life Bottle! Time Marked Water Bottle - 1 Gallon Water Bottle with Time Marker - Extra Large Water Bottle/Water Jug Helps You Drink More Water! BPA Free Water Bottle with Leakproof Flip Top
    [2] Venture Pal Large 1 Gallon Motivational Water Bottle with 2 Lids (Chug and Straw), Leakproof BPA Free Tritan Sports Water Jug with Time Marker to Ensure You Drink Enough Water Throughout The Day
    [2] Giotto Large 1 Gallon Motivational Water Bottle with Paracord Handle & Removable Straw - Leakproof Tritan BPA Free Fitness Sports Water Jug with Time Marker-1G-Orange/Green Gradient
    [2] Motivational Water Bottle with Time Marker & Hourly Hydration Measurements – BPA Free & Non Toxic Large Sports Fitness Bottle Jug with Wide Mouth – Ensure You Drink Enough Water (Blue)
  top predicted (BM25):
    [0] Spout Lid for Hydro Flask Wide Mouth Sport Water Bottles, Replacement Lid Accessories for Hydro Flask Chug lid with Big Handle Easy to Carry, Fits Most Wide Mouth Bottles
    [0] SENDESTAR Straw Lid for Hydro Flask Wide Mouth Sports Water Bottle with 2 Straws and 1 Brush (Black)
    [0] SENDESTAR Straw Lid for Hydro Flask Wide Mouth Sports Water Bottle with 2 Straws and 1 Brush (Pink)
    [0] THVALUE 24 oz Leak Proof Reusable Water Bottles Clear Water Bottle with Ice Stick
    [0] 100 Pcs Inspirational Words Stickers for Motivational Quote Stickers for Teens and Adults Trendy Vinyl Positive Sticker for Water Bottles Book Laptop

==================== BEST 10 (highest NDCG@10) ====================

query_id=81394  query='ployes'
  top judged-relevant products for this query:
    [3] Ployes - French Acadian Buckwheat Pancake - Flatbread Mix, Large 3 Pound Bag
    [3] Pulp, Potatoes, And Ployes: An Acadian Odyssey
    [3] PLOYES Mix Pancake Unbl Wheat And Buckwheat, 24 OZ
    [0] Bouchard Family Farms Gluten-Free and Kosher Acadian Light Buckwheat Flour, 3lb Bag
    [0] L'approche du mal: L'expert psychologue des Fourniret, de Francis Heaulme et de Pierre Chanal raconte (Documents Français) (French Edition)
  top predicted (BM25):
    [3] PLOYES Mix Pancake Unbl Wheat And Buckwheat, 24 OZ
    [3] Pulp, Potatoes, And Ployes: An Acadian Odyssey
    [3] Ployes - French Acadian Buckwheat Pancake - Flatbread Mix, Large 3 Pound Bag
    [0] Amazon Basics Woodcased #2 Pencils, Unsharpened, HB Lead - Box of 144, Bulk Box
    [0] BAZIC Pencil #2 HB Pencils, Latex Free Eraser, Wood Free Yellow Unsharpened Pencils for Exam School Office (12/Pack), 1-Pack

query_id=84395  query='pur pitcher water filters'
  top judged-relevant products for this query:
    [3] PUR Pitcher Replacement Filter, 6 Count (Pack of 1), AS Shown
    [3] PUR Filters, Pack of 3, 3 Count
    [3] PUR Water Pitcher Replacement Filter, 4 Count (Pack of 1), Blue
    [3] PUR PLUS Large Filtered Water Dispenser, 30 Cup – Includes 1 PUR PLUS Water Pitcher Filter
    [3] PUR MAXION Replacement Pitcher Filter - 4 PACK
  top predicted (BM25):
    [3] PUR Basic Water Pitcher Replacement Filter, 2-Stage, 1-Pack, Filter Replacements for PUR Water Filter Pitchers, Reduced Chlorine Taste and Odor, Filters Provide 40 Gallons/2 Months of Filtered Water
    [3] PUR Filters, Pack of 3, 3 Count
    [3] PUR Water Pitcher Replacement Filter, 4 Count (Pack of 1), Blue
    [3] PUR Water Pitcher Replacement Filter with Lead Reduction, 3 Pack, Blue Packaging May Vary
    [3] PUR CR1100CV Classic Water Filter Pitcher Filtration System, 11 Cup

query_id=14725  query='behind her eyes'
  top judged-relevant products for this query:
    [3] Behind Her Eyes: A Novel
    [0] Behind Closed Doors
    [0] Your Name Is a Song
    [0] Dead to Her: A Novel
    [0] If You Tell: A True Story of Murder, Family Secrets, and the Unbreakable Bond of Sisterhood
  top predicted (BM25):
    [3] Behind Her Eyes: A Novel
    [0] Behind Her Eyes (A Riley Thompson Thriller Book 1)
    [0] FurReal Flitter The Kitten Color-Change Interactive Feeding Toy, Lights and Sounds, Ages 4 and up
    [0] The Naked Truth: The Real Story Behind the Real Housewife of New Jersey--In Her Own Words
    [0] Baby Born Surprise Bathtub Surprise Purple Swaddle Princess

query_id=46149  query='gm original equipment ignition knock'
  top judged-relevant products for this query:
    [3] 213-3521 GM Original Equipment Ignition Knock (Detonation) Sensor
    [3] ACDelco GM Original Equipment 12636736 Ignition Knock (Detonation) Sensor
    [3] ACDelco GM Original Equipment 213-4335 Ignition Knock (Detonation) Sensor
    [3] ACDelco 93440806 GM Original Equipment Ignition Distributor
    [3] ACDelco GM Original Equipment 213-3522 Ignition Knock (Detonation) Sensor
  top predicted (BM25):
    [3] 213-3521 GM Original Equipment Ignition Knock (Detonation) Sensor
    [3] ACDelco GM Original Equipment 12636736 Ignition Knock (Detonation) Sensor
    [3] ACDelco GM Original Equipment 213-2829 Ignition Knock (Detonation) Sensor
    [3] ACDelco GM Original Equipment 213-92 Ignition Knock (Detonation) Sensor
    [3] ACDelco 213-94 GM Original Equipment Ignition Knock (Detonation) Sensor

query_id=61620  query='leteulo crossbody'
  top judged-relevant products for this query:
    [3] Crossbody Bag for Women Genuine Leather Vintage Purses Clutch Handbag (Brown)
    [3] Womens Crossbody Purse Wristlet Clutch Handbags Leather Shoulder Bag (L,brown)
    [2] Crossbody Bag Classic Vintage Shoulder Bag Zipper Purse (Coffee)
    [0] TUMI - Monaco Folding Card Case Wallet for Men - Black
    [0] TUMI - Belden Travel Wallet - Red
  top predicted (BM25):
    [3] Womens Crossbody Purse Wristlet Clutch Handbags Leather Shoulder Bag (L,brown)
    [3] Crossbody Bag for Women Genuine Leather Vintage Purses Clutch Handbag (Brown)
    [2] Crossbody Bag Classic Vintage Shoulder Bag Zipper Purse (Coffee)
    [0] Nine West womens Crossbody,Black,Medium
    [0] Handbag On Sale,Clearance!AgrinTol Women Fashion Handbag Shoulder Bag Tote Ladies Purse (Gray)

query_id=104288  query='toronto blue jays cap'
  top judged-relevant products for this query:
    [3] New Era MLB 2019 Armed Forces Day 9Twenty Adjustable Dad Hat Cap: OSFM (Toronto Blue Jays)